### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by jurgenhaas** [rM-self-serve/webinterface-wifi#1]
This looks really great. Gave it a try and was able to install it and run it on the RM but I can't connect from the host's browser. When doing `curl http://1.2.3.4` it responds with "Connection refused".

The process on the RM is running, though.

I've also tried with a different port, no luck either.

Any idea what could be the reason? The release on my RM is 3.2.3.1595

**Comment by rM-self-serve** [comment]
Apologies for the late reply but thanks both for trying it out and the feedback! It's a little bit tough to figure where the issue may be.

This program alone has some limitations that I likely could elaborate on in the readme, just want to make sure that's not the case here. The web interface will only be available over wifi if the device is plugged in and the web interface is enabled and reachable at 10.11.99.1. Could elaborate on not requiring the cord.

If the above is true and still no luck, I will go ahead and give it a test on that version soon. Wouldn't hurt to try running a simple web server on the wifi interface to ensure the issue is with this reverse-proxy.

**Comment by jurgenhaas** [comment]
Thanks for getting back on this. The task has slipped priority at my side since I've posted this, so I won't be able to test this again any time soon. But I recall that my device wasn't plugged - so that might have been the reason.

**Comment by rM-self-serve** [comment]
You can check out my new repos to make webinterface-wifi work without any cable! 

https://github.com/rM-self-serve/webinterface-onboot

https://github.com/rM-self-serve/webinterface-persist-ip
