### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by robinshields** [rM-self-serve/webinterface-wifi#3]
Hi - This is a great idea, but having trouble getting it running. Here's a summary that I hope can help:

- Software 3.4.1.1790 
- Installed normally via opkg
- Also enabled normally via systemctl, and **device is connected by USB**
- Web browser quickly returns connection refused, suggesting remarkable actively refused it (different from an IP for a non-existent device on the local WiFi, which takes a long time to timeout).
- Tried changing the port incase that is issue (to 8080)
- `ps` command shows it is running `/opt/bin/webinterface-wifi --run 8080`
- `netstat -lntu` suggests port never opened successfully (8080 not listed)
- It seems it is failing somewhere, silently
- Also tried running manually `webinterface-wifi --run 8181` - there is no output in the terminal but it does not work

Thanks for making this package, would be great to get it working.

**Comment by rM-self-serve** [comment]
Hello, I am sorry for the delay. I did not have any suspicions of the bug at the time nor a good way to debug such issues. 

v2 has just been released and is built more transparently. There are a few built in ways to debug network issues and server state. If is something you decide to try and still run into issues, I will be happy to help resolve them. I have a suspicion that the usb0 interface had multiple ip addrs, this is fixed in v2.

It may be a little time before it is updated in Toltec. Thanks.
